<?php
function asciihtml($text){
	//$text = str_replace('<', '&lt;', $text); //<
	//$text = str_replace('>', '&gt;', $text); //>
	$text = str_replace(chr(4), '<p>', $text); //[Ctrl]-[Enter]
	$text = str_replace(chr(159), 'f', $text); //f gulden teken
	//$text = str_replace(chr(0128), '&euro;', $text); //euro
	$text = str_replace(chr(134),'&aring;', $text); //å
	$text = str_replace(chr(143),'&Aring;', $text); //Å
	$text = str_replace(chr(132),'&auml;', $text); //ä
	$text = str_replace(chr(142),'&Auml;', $text); //Ä
	$text = str_replace(chr(160),'&aacute;', $text); //á
	$text = str_replace(chr(181),'&Aacute;', $text); //Á
	$text = str_replace(chr(133),'&agrave;', $text); //à
	$text = str_replace(chr(183),'&Agrave;', $text); //À
	$text = str_replace(chr(145),'&aelig;', $text); //æ
	$text = str_replace(chr(146),'&Aelig;', $text); //Æ
	$text = str_replace(chr(143),'&Acirc;', $text); //Â
	$text = str_replace(chr(131),'&acirc;', $text); //â
	$text = str_replace(chr(198),'&atilde;', $text); //ã
	$text = str_replace(chr(199),'&Atilde;', $text); //Ã
	$text = str_replace(chr(135),'&ccedil;', $text); //ç
	$text = str_replace(chr(128),'&Ccedil;', $text); //Ç
	$text = str_replace(chr(130),'&eacute;', $text); //é
	$text = str_replace(chr(144),'&Eacute;', $text); //É
	$text = str_replace(chr(136),'&ecirc;', $text); //ê
	$text = str_replace(chr(210),'&Ecirc;', $text); //Ê
	$text = str_replace(chr(137),'&euml;', $text); //ë
	$text = str_replace(chr(211),'&Euml;', $text); //Ë
	$text = str_replace(chr(138),'&egrave;', $text); //è
	$text = str_replace(chr(212),'&Egrave;', $text); //È
	$text = str_replace(chr(140),'&icirc;', $text); //î
	$text = str_replace(chr(215),'&Icirc;', $text); //Î
	$text = str_replace(chr(161),'&iacute;', $text); //í
	$text = str_replace(chr(214),'&Iacute;', $text); //Í
	$text = str_replace(chr(141),'&igrave;', $text); //ì
	$text = str_replace(chr(222),'&Igrave;', $text); //Ì
	$text = str_replace(chr(139),'&iuml;', $text); //ï
	$text = str_replace(chr(216),'&Iuml;', $text); //Ï
	$text = str_replace(chr(164),'&ntilde;', $text); //ñ
	$text = str_replace(chr(165),'&Ntilde;', $text); //Ñ
	$text = str_replace(chr(148),'&ouml;', $text); //ö
	$text = str_replace(chr(153),'&Ouml;', $text); //Ö
	$text = str_replace(chr(149),'&ograve;', $text); //ò
	$text = str_replace(chr(227),'&Ograve;', $text); //Ò
	$text = str_replace(chr(162),'&oacute;', $text); //ó
	$text = str_replace(chr(224),'&Oacute;', $text); //Ó
	$text = str_replace(chr(155),'&oslash;', $text); //ø
	$text = str_replace(chr(157),'&Oslash;', $text); //Ø
	$text = str_replace(chr(148),'&ocirc;', $text); //ô
	$text = str_replace(chr(226),'&Ocirc;', $text); //Ô
	$text = str_replace(chr(228),'&otilde;', $text); //õ
	$text = str_replace(chr(229),'&Otilde;', $text); //Õ
	$text = str_replace(chr(129),'&uuml;', $text); //ü
	$text = str_replace(chr(154),'&Uuml;', $text); //Ü
	$text = str_replace(chr(163),'&uacute;', $text); //ú
	$text = str_replace(chr(233),'&Uacute;', $text); //Ú
	$text = str_replace(chr(235),'&Ugrave;', $text); //Ù
	$text = str_replace(chr(151),'&ugrave;', $text); //ù
	$text = str_replace(chr(150),'&ucirc;', $text); //û
	$text = str_replace(chr(234),'&Ucirc;', $text); //Û
	$text = str_replace(chr(236),'&yacute;', $text); //ý
	$text = str_replace(chr(237),'&Yacute;', $text); //Ý
	$text = str_replace(chr(152),'&yuml;', $text); //ÿ
	$text = str_replace(chr(39),'&#039;', $text); //'
	return $text;
}
?>